version: '3'
services:
  node:
    build:
      context: ./react
    volumes:
      - ./react:/usr/src/app
    command: sh -c "cd react-sample && yarn start"
    ports:
      - "3001:3000"
  nginx:
    depends_on:
      - node
      - api
    build:
      context: ./nginx
    volumes:
      - ./nginx/my.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    command: >
      sh -c "json-server 
      --host 0.0.0.0
      --routes routes.json
      --watch db.json"
      --port 3000
    ports:
      - "3000:3000"
